
import json
from argparse import ArgumentParser


from biocommons.seqrepo import SeqRepo
from ga4gh.vrs.dataproxy import SeqRepoDataProxy
from ga4gh.vrs.extras.translator import AlleleTranslator

def get_seqrepo():
    return SeqRepo('/usr/local/share/seqrepo/2024-12-20')

def get_translator():
    seq_repo = get_seqrepo()
    translator = AlleleTranslator(data_proxy=SeqRepoDataProxy(seq_repo))
    return translator

# the spdi generated by vrs is in this format: SEQUENCE-ID:POSITION:DEL-LEN:INS-SEQUENCE
# need to convert to this format for igvf catalog: SEQUENCE-ID:POSITION:DEL-SEQUENCE:INS-SEQUENCE
def convert_spdi(spdi, seq):
    ls = spdi.split(':')
    ls[2] = seq
    spdi = ':'.join(ls)
    return spdi

def get_allele_from_hgvs(hgvs_string, translator):
    return translator.translate_from(hgvs_string, 'hgvs')

def build_spdi_from_allele(allele, translator):
    spdi = translator.translate_to(allele, 'spdi')[0]
    del_seq = translator.data_proxy.get_sequence(
        f'ga4gh:{allele.location.sequenceReference.refgetAccession}',
        allele.location.start,
        allele.location.end)
    spdi = convert_spdi(spdi, del_seq)
    return spdi





def main():
    parser = ArgumentParser()
    parser.add_argument("--input_file", type=str, help="Input JSONL file")
    parser.add_argument("--output_file", type=str, help="Output JSONL file")
    args = parser.parse_args()

    translator = get_translator()

    with open(args.input_file, "r") as f_in, open(args.output_file, "w") as f_out:
        for line in f_in:
            data = json.loads(line)
            hgvs_string = data["hgvs"]
            ca_id = data["ca_id"]
            allele = get_allele_from_hgvs(hgvs_string, translator)
            spdi = build_spdi_from_allele(allele, translator)
            key = spdi if len(spdi) < 254 else allele.digest
            f_out.write(json.dumps({"hgvs": hgvs_string, "ca_id": ca_id, "_key": key}) + "\n")

if __name__ == "__main__":
    main()